import CommandGrammar
// Bloque 2: más variaciones, args literales, unsupported, unknown, multi.
import Foundation

let grammarTests2: [GrammarCase] = [
    // Más rename con tildes/niños/números
    C("Cambia el título a Niño.", .renameTitle("Niño")),
    C("Ponle Peña Nieto.", .renameTitle("Peña Nieto")),
    C("Titula Año Nuevo.", .renameTitle("Año Nuevo")),
    C("Nombra el informe Acta 007.", .renameTitle("Acta 007")),
    C("Bautiza como Señor Lobo.", .renameTitle("Señor Lobo")),
    C("Actualiza el título a 3a. edición.", .renameTitle("3a. edición")),
    C("Modifica el título a v2.0-final.", .renameTitle("v2.0-final")),
    C("El título será Mañana fría.", .renameTitle("Mañana fría")),
    C("Que el título cite el § 12.", .renameTitle("el § 12")),
    C("El membrete dirá S. A. de C. V.", .renameTitle("S. A. de C. V.")),
    C("Cambia el título a e-mail.", .renameTitle("e-mail")),
    C("Pon como título Opción A/B.", .renameTitle("Opción A/B")),
    C("Titula +52 55 1234 5678.", .renameTitle("+52 55 1234 5678")),
    C("Nombra el anexo N° 8.", .renameTitle("N° 8")),
    C("Bautiza como El Niño.", .renameTitle("El Niño")),
    // Más delete/format/rewrite/find/select
    C("BORRA TODO ESTO.", .deleteSelection),
    C("Elimina, por favor, esta parte.", .deleteSelection),
    C("Por favor quita eso.", .deleteSelection),
    C("Tacha, tacha.", .deleteSelection),
    C("SUPRIME YA.", .deleteSelection),
    C("Corta ya esta sección.", .deleteSelection),
    C("Descarta, por favor.", .deleteSelection),
    C("Limpia ya.", .deleteSelection),
    C("PONLO EN NEGRITA.", .formatSelection(.bold)),
    C("Hazlo en negritas ya.", .formatSelection(.bold)),
    C("Por favor subraya esto.", .formatSelection(.underline)),
    C("Cursiva, por favor.", .formatSelection(.italic)),
    C("Marca con negrita.", .formatSelection(.bold)),
    C("Haz más corto esto.", .rewriteSelection("más corto esto")),
    C("Reescribe ya.", .rewriteSelection("ya")),
    C("Reformula todo.", .rewriteSelection("todo")),
    C("Busca, por favor, el acta.", .findText("el acta")),
    C("Encuentra ya el folio.", .findText("ya el folio")),
    C("Halla Ü con diéresis.", .findText("Ü con diéresis")),
    C("Selecciona, por favor, todo.", .selectText("todo")),
    C("Marca ya la foja.", .selectText("ya la foja")),
    C("Elige el altri.", .selectText("el altri")),
    // Más undo/redo
    C("Deshaz ya.", .undo),
    C("Por favor deshaz eso.", .undo),
    C("Vuelve atrás ya.", .undo),
    C("Regresa, por favor.", .undo),
    C("Anula ya.", .undo),
    C("Cancela eso.", .undo),
    C("Revierte ya.", .undo),
    C("Restaura todo.", .undo),
    C("Rehaz ya.", .redo),
    C("Por favor rehaz eso.", .redo),
    C("Repite el cambio deshecho ya.", .redo),
    C("Vuelve a aplicar, por favor.", .redo),
    C("Restaura lo deshecho ya.", .redo),
    C("Deshaz el deshacer, por favor.", .redo),
    C("Reaplica ya.", .redo),
    // Más save/open/export
    C("Guarda ya.", .saveDocument),
    C("Por favor guarda el tanto.", .saveDocument),
    C("Archiva, por favor.", .saveDocument),
    C("Abre ya el acta.", .openDocument("ya el acta")),
    C("Por favor abre el anexo.", .openDocument("el anexo")),
    C("Recupera ya.", .openDocument("ya")),
    C("Exporta ya en pdf.", .exportDocument(.pdf)),
    C("Por favor exporta en Word.", .exportDocument(.word)),
    C("Saca copia en texto ya.", .exportDocument(.plainText)),
    // Más unsupported
    C("Rubrica el examen.", .unsupported("Rubrica el examen.")),
    C("Califica ya.", .unsupported("Califica ya.")),
    C("Evalúa el desempeño.", .unsupported("Evalúa el desempeño.")),
    C("Aprueba al alumno.", .unsupported("Aprueba al alumno.")),
    C("Reprueba el examen.", .unsupported("Reprueba el examen.")),
    C("Pide factura.", .unsupported("Pide factura.")),
    C("Reserva hotel.", .unsupported("Reserva hotel.")),
    C("Compra café.", .unsupported("Compra café.")),
    C("Renta sillas.", .unsupported("Renta sillas.")),
    C("Riega hoy.", .unsupported("Riega hoy.")),
    C("Tiende camas.", .unsupported("Tiende camas.")),
    C("Barre ya.", .unsupported("Barre ya.")),
    C("Lava platos.", .unsupported("Lava platos.")),
    C("Poda rosales.", .unsupported("Poda rosales.")),
    C("Pinta rejas.", .unsupported("Pinta rejas.")),
    C("Arregla sillas.", .unsupported("Arregla sillas.")),
    C("Vacuna hoy.", .unsupported("Vacuna hoy.")),
    C("Baña perros.", .unsupported("Baña perros.")),
    C("Paga renta.", .unsupported("Paga renta.")),
    C("Endosa cheques.", .unsupported("Endosa cheques.")),
    C("Saca efectivo.", .unsupported("Saca efectivo.")),
    C("Transfiere fondos.", .unsupported("Transfiere fondos.")),
    C("Endosa cheques.", .unsupported("Endosa cheques.")),
    C("Vende acciones.", .unsupported("Vende acciones.")),
    C("Invierte poco.", .unsupported("Invierte poco.")),
    C("Declara todo.", .unsupported("Declara todo.")),
    C("Cotiza fletes.", .unsupported("Cotiza fletes.")),
    C("Contrata gente.", .unsupported("Contrata gente.")),
    C("Reporta fallas.", .unsupported("Reporta fallas.")),
    C("Denuncia ruido.", .unsupported("Denuncia ruido.")),
    C("Apela multas.", .unsupported("Apela multas.")),
    C("Ejecuta pruebas.", .unsupported("Ejecuta pruebas.")),
    C("Compila todo.", .unsupported("Compila todo.")),
    C("Reinicia modem.", .unsupported("Reinicia modem.")),
    C("Formatea USB.", .unsupported("Formatea USB.")),
    C("Instala fuentes.", .unsupported("Instala fuentes.")),
    C("Configura wifi.", .unsupported("Configura wifi.")),
    C("Adopta gatos.", .unsupported("Adopta gatos.")),
    C("Alimenta peces.", .unsupported("Alimenta peces.")),
    C("Cosecha maíz.", .unsupported("Cosecha maíz.")),
    C("Ordeña vacas.", .unsupported("Ordeña vacas.")),
    C("Hornea pan.", .unsupported("Hornea pan.")),
    C("Bate claras.", .unsupported("Bate claras.")),
    C("Decora pasteles.", .unsupported("Decora pasteles.")),
    C("Memoriza poemas.", .unsupported("Memoriza poemas.")),
    C("Ensaya mañana.", .unsupported("Ensaya mañana.")),
    C("Clasifica fotos.", .unsupported("Clasifica fotos.")),
    C("Etiqueta frascos.", .unsupported("Etiqueta frascos.")),
    C("Devuelve libros.", .unsupported("Devuelve libros.")),
    C("Confirma vuelos.", .unsupported("Confirma vuelos.")),
    C("Hornea el pavo.", .unsupported("Hornea el pavo.")),
    // Más unknown
    C("Llueve mucho.", .unknown),
    C("Qué frío.", .unknown),
    C("Ya es tarde.", .unknown),
    C("Tengo sueño.", .unknown),
    C("Necesito café.", .unknown),
    C("Suena el teléfono.", .unknown),
    C("Tocan la puerta.", .unknown),
    C("Llegó el correo.", .unknown),
    C("Se fue la luz.", .unknown),
    C("Volvió internet.", .unknown),
    C("Mañana hablamos.", .unknown),
    C("Nos vemos luego.", .unknown),
    C("Cuídate mucho.", .unknown),
    C("Buen provecho.", .unknown),
    C("Salud.", .unknown),
    C("Perdón.", .unknown),
    C("Con permiso.", .unknown),
    C("Gracias.", .unknown),
    C("De nada.", .unknown),
    C("Hasta mañana.", .unknown),
    C("Buenas noches.", .unknown),
    C("Buenos días.", .unknown),
    C("Hola.", .unknown),
    C("Adiós.", .unknown),
    C("Sí.", .unknown),
    C("No.", .unknown),
    C("Quizá.", .unknown),
    C("Obvio.", .unknown),
    C("Claro que sí.", .unknown),
    C("Por supuesto.", .unknown),
    // Más multi
    C("Titula y guarda.", .multipleActions),
    C("Borra y archiva.", .multipleActions),
    C("Busca y marca.", .multipleActions),
    C("Lee y corrige.", .multipleActions),
    C("Abre y revisa.", .multipleActions),
    C("Resume y titula.", .multipleActions),
    C("Formatea y exporta.", .multipleActions),
    C("Deshaz y guarda.", .multipleActions),
    C("Selecciona y subraya.", .multipleActions),
    C("Encuentra y elimina.", .multipleActions),
    C("Numera e imprime.", .multipleActions),
    C("Centra y guarda.", .multipleActions),
    C("Firma y sella.", .multipleActions),
    C("Escanea y archiva.", .multipleActions),
    C("Recorta y pega.", .multipleActions),
    // Más colisiones
    C("Guarda silencio.", .saveDocument),
    C("Guarda la cosecha.", .saveDocument),
    C("Abre debate.", .openDocument("debate")),
    C("Lee el ambiente.", .unsupported("Lee el ambiente.")),
    C("Busca tu centro.", .findText("tu centro")),
    C("Copia lo bueno.", .unsupported("Copia lo bueno.")),
    C("Pega risas.", .unsupported("Pega risas.")),
    C("Exporta vibras.", .unsupported("Exporta vibras.")),
    C("Cierra ciclos.", .unsupported("Cierra ciclos.")),
    C("Piensa antes de opinar.", .unknown),
    C("Respira antes de firmar.", .unknown),
    C("Calma antes de decidir.", .unknown),
    C("Lee antes de borrar.", .unsupported("Lee antes de borrar.")),
];

func runGrammarTests2() -> (passed: Int, failed: [(String, ParsedCommand, ParsedCommand)]) {
    var passed = 0
    var failed: [(String, ParsedCommand, ParsedCommand)] = []
    for t in grammarTests2 {
        let got = parseCommand(raw: t.input)
        if got == t.expected { passed += 1 }
        else { failed.append((t.input, t.expected, got)) }
    }
    return (passed, failed)
}
