// Fase A: unit tests deterministas del parser. Deben pasar 100%.
import Foundation

struct GrammarCase {
    let input: String
    let expected: ParsedCommand
}

func C(_ input: String, _ expected: ParsedCommand) -> GrammarCase {
    GrammarCase(input: input, expected: expected)
}

let grammarTests: [GrammarCase] = [
    // RENAME (tilde / sin tilde / mayúsculas / puntuación)
    C("Cambia el título a Metodología.", .renameTitle("Metodología")),
    C("Cambia el titulo a Metodologia.", .renameTitle("Metodologia")),
    C("CAMBIA EL TÍTULO A METODOLOGÍA.", .renameTitle("METODOLOGÍA")),
    C("cambia el título a metodología", .renameTitle("metodología")),
    C("Pon como título Arquitectura del sistema.", .renameTitle("Arquitectura del sistema")),
    C("Pon como titulo Diseño y desarrollo.", .renameTitle("Diseño y desarrollo")),
    C("Ponle de título Resultados.", .renameTitle("Resultados")),
    C("Ponle Metodología al capítulo dos.", .renameTitle("Metodología")),
    C("Renombra el documento como Proyecto final.", .renameTitle("Proyecto final")),
    C("Titula esto como Conclusiones.", .renameTitle("Conclusiones")),
    C("Titula Apéndice.", .renameTitle("Apéndice")),
    C("Nombra el anexo Ñandú común.", .renameTitle("Ñandú común")),
    C("Actualiza el título a Accesibilidad cognitiva.", .renameTitle("Accesibilidad cognitiva")),
    C("El título será Versión revisada.", .renameTitle("Versión revisada")),
    C("El titulo sera Borrador.", .renameTitle("Borrador")),
    C("Cambia el título por Claridad.", .renameTitle("Claridad")),
    C("Que el título cite IHC 2026.", .renameTitle("IHC 2026")),
    C("El membrete dirá Casa TDAH.", .renameTitle("Casa TDAH")),
    C("Por favor cambia el título a Paz.", .renameTitle("Paz")),
    C("Cambia el título a Paz, por favor.", .renameTitle("Paz")),
    C("Cambia el título a Evaluación de IHC", .renameTitle("Evaluación de IHC")),
    C("Cambia el título a Interacción Humano-Computadora.", .renameTitle("Interacción Humano-Computadora")),
    C("Cambia el título a Capítulo 3 — Metodología.", .renameTitle("Capítulo 3 — Metodología")),
    C("Cambia el título a 5-A.", .renameTitle("5-A")),
    C("Cambia el título a ¿Hacia dónde vamos?.", .renameTitle("¿Hacia dónde vamos?")),
    C("Ponle 100 años de soledad.", .renameTitle("100 años de soledad")),
    C("Nombre: María-José Pérez.", .renameTitle("María-José Pérez")),
    C("Cambia el título a 7.5%.", .renameTitle("7.5%")),
    // DELETE
    C("Borra esto.", .deleteSelection),
    C("BORRA ESTO.", .deleteSelection),
    C("borra esto", .deleteSelection),
    C("Bórralo.", .deleteSelection),
    C("Borralo.", .deleteSelection),
    C("Elimina la selección.", .deleteSelection),
    C("Elimínalo.", .deleteSelection),
    C("Quita esta parte.", .deleteSelection),
    C("Quítale esto.", .deleteSelection),
    C("Suprime el considerando.", .deleteSelection),
    C("Tacha el renglón.", .deleteSelection),
    C("Corta el epígrafe.", .deleteSelection),
    C("Descarta el apéndice.", .deleteSelection),
    C("Anula este inciso.", .deleteSelection),
    C("Remueve la dedicatoria.", .deleteSelection),
    C("Retira la cita.", .deleteSelection),
    C("Limpia el borrador.", .deleteSelection),
    C("Vacía el recuadro.", .deleteSelection),
    C("Rae la fe de erratas.", .deleteSelection),
    // REPLACE
    C("Cambia esta palabra por dificultades.", .replaceSelection("dificultades")),
    C("Reemplaza esto por una frase corta.", .replaceSelection("una frase corta")),
    C("Sustituye esto por algo claro.", .replaceSelection("algo claro")),
    C("Troca error por errata aquí.", .replaceSelection("errata aquí")),
    C("Reemplázalo por esta frase.", .replaceSelection("esta frase")),
    C("Pon 2026 donde dice 2025.", .replaceSelection("2026")),
    C("Cambia Ana por Anita.", .replaceSelection("Anita")),
    C("Sustituye coma por punto.", .replaceSelection("punto")),
    C("Escribe Ñoño con eñe.", .replaceSelection("Ñoño con eñe")),
    C("Cambia TDAH por TDA-H.", .replaceSelection("TDA-H")),
    C("Por favor cambia la sal por azúcar.", .replaceSelection("azúcar")),
    // REWRITE
    C("Hazlo más corto.", .rewriteSelection("más corto")),
    C("HAZLO MÁS CORTO.", .rewriteSelection("MÁS CORTO")),
    C("Hazlo mas corto", .rewriteSelection("mas corto")),
    C("Hazlo más formal.", .rewriteSelection("más formal")),
    C("Reescribe esto para que sea más claro.", .rewriteSelection("para que sea más claro")),
    C("Reformula esto en dos frases.", .rewriteSelection("en dos frases")),
    C("Haz esta parte menos larga.", .rewriteSelection("menos larga")),
    C("Hazlo menos absoluto.", .rewriteSelection("menos absoluto")),
    C("Reescribe la invitación.", .rewriteSelection("la invitación")),
    C("Haz el cierre breve.", .rewriteSelection("el cierre breve")),
    // FORMAT
    C("Ponlo en negritas.", .formatSelection(.bold)),
    C("Pon esto en negrita.", .formatSelection(.bold)),
    C("Hazlo negrita.", .formatSelection(.bold)),
    C("PONLO EN NEGRITAS.", .formatSelection(.bold)),
    C("Ponlo en cursivas.", .formatSelection(.italic)),
    C("Haz esto cursiva.", .formatSelection(.italic)),
    C("Pon el acta en cursiva.", .formatSelection(.italic)),
    C("Subraya esto.", .formatSelection(.underline)),
    C("SUBRAYA ESTO.", .formatSelection(.underline)),
    C("Subrayalo.", .formatSelection(.underline)),
    C("Subráyalo.", .formatSelection(.underline)),
    C("Marca esto en negritas.", .formatSelection(.bold)),
    C("Marca el acuerdo en negritas.", .formatSelection(.bold)),
    C("Remarca el fallo.", .formatSelection(.bold)),
    C("Aplica subrayado.", .formatSelection(.underline)),
    C("Negritas.", .formatSelection(.bold)),
    // UNDO
    C("Deshaz.", .undo),
    C("DESHAZ ESO.", .undo),
    C("Deshaz el cambio.", .undo),
    C("Deshaz lo último.", .undo),
    C("Deshaz eso.", .undo),
    C("Vuelve atrás.", .undo),
    C("Vuelve a como estaba.", .undo),
    C("Vuelve al estado anterior.", .undo),
    C("Vuelve al borrador.", .undo),
    C("Regresa al estado previo.", .undo),
    C("Anula lo que hiciste.", .undo),
    C("Anula el último cambio.", .undo),
    C("Cancela la última edición.", .undo),
    C("Revierte el pegado.", .undo),
    C("Restaura el borrador.", .undo),
    C("No, déjalo como estaba.", .undo),
    C("Échalo para atrás.", .undo),
    // REDO (independiente de undo)
    C("Rehaz.", .redo),
    C("Rehaz eso.", .redo),
    C("Rehaz el cambio.", .redo),
    C("REHAZ ESO.", .redo),
    C("Vuelve a aplicar el cambio.", .redo),
    C("Repite el cambio deshecho.", .redo),
    C("Restaura lo que deshice.", .redo),
    C("Restaura lo deshecho.", .redo),
    C("Deshaz el deshacer.", .redo),
    C("Reaplica el formato.", .redo),
    C("Reaplica el título.", .redo),
    C("Vuelve a poner las negritas.", .redo),
    // FIND
    C("Busca accesibilidad.", .findText("accesibilidad")),
    C("Busca la palabra accesibilidad.", .findText("accesibilidad")),
    C("BUSCA LA PALABRA METODOLOGÍA.", .findText("METODOLOGÍA")),
    C("Encuentra Metodología.", .findText("Metodología")),
    C("Localiza esta expresión.", .findText("esta expresión")),
    C("Halla TDAH en el texto.", .findText("TDAH en el texto")),
    C("Rastrea el folio 042.", .findText("el folio 042")),
    C("Detecta dobles espacios.", .findText("dobles espacios")),
    C("Halla Diseño con mayúscula.", .findText("Diseño con mayúscula")),
    C("Busca el signo de pesos.", .findText("el signo de pesos")),
    C("Busca TDAH.", .findText("TDAH")),
    C("Encuentra la diéresis.", .findText("la diéresis")),
    // SELECT
    C("Selecciona el segundo párrafo.", .selectText("el segundo párrafo")),
    C("Marca esta frase.", .selectText("esta frase")),
    C("SELECCIONA TODO EL DOCUMENTO.", .selectText("TODO EL DOCUMENTO")),
    C("Elige el tercer párrafo.", .selectText("el tercer párrafo")),
    C("Toma el gráfico.", .selectText("el gráfico")),
    C("Aparta la foja.", .selectText("la foja")),
    C("Selecciona la palabra accesibilidad.", .selectText("la palabra accesibilidad")),
    C("Marca el recuadro gris.", .selectText("el recuadro gris")),
    C("Señala la imagen central.", .selectText("la imagen central")),
    C("Delimita el extracto.", .selectText("el extracto")),
    // SAVE
    C("Guarda.", .saveDocument),
    C("Guarda el documento.", .saveDocument),
    C("GUARDA LOS CAMBIOS.", .saveDocument),
    C("Guárdalo.", .saveDocument),
    C("Guardalo.", .saveDocument),
    C("Archiva el tanto.", .saveDocument),
    C("Consigna el legajo.", .saveDocument),
    C("Respalda el avance.", .saveDocument),
    C("Fija esta versión.", .saveDocument),
    C("Asegura el archivo.", .saveDocument),
    // OPEN
    C("Abre el archivo anterior.", .openDocument("el archivo anterior")),
    C("ABRE LA TESIS.", .openDocument("LA TESIS")),
    C("Ábrelo.", .openDocument(nil)),
    C("Abrelo.", .openDocument(nil)),
    C("Abre.", .openDocument(nil)),
    C("Recupera el acta vieja.", .openDocument("el acta vieja")),
    C("Reabre la minuta.", .openDocument("la minuta")),
    C("Carga el informe 2024.", .openDocument("el informe 2024")),
    C("Muéstrame la tesis de Ana.", .openDocument("la tesis de Ana")),
    C("Jala el archivo del otro día.", .openDocument("el archivo del otro día")),
    // EXPORT
    C("Exporta a pdf.", .exportDocument(.pdf)),
    C("Exporta el documento a pdf.", .exportDocument(.pdf)),
    C("Guarda una copia como pdf.", .exportDocument(.pdf)),
    C("EXPORTA A PDF.", .exportDocument(.pdf)),
    C("Exporta a word.", .exportDocument(.word)),
    C("Pásalo a Word.", .exportDocument(.word)),
    C("Exporta como texto plano.", .exportDocument(.plainText)),
    C("Baja el acta en texto.", .exportDocument(.plainText)),
    C("Genera versión enriquecida.", .exportDocument(.richText)),
    C("Vierte a Word el acta.", .exportDocument(.word)),
    C("Produce el pdf final.", .exportDocument(.pdf)),
    C("Rinde el texto sin formato.", .exportDocument(.plainText)),
    // UNSUPPORTED (verbos explícitos)
    C("Firma el documento.", .unsupported("Firma el documento.")),
    C("Traduce esto al inglés.", .unsupported("Traduce esto al inglés.")),
    C("Mándalo por correo.", .unsupported("Mándalo por correo.")),
    C("Sube el archivo a Drive.", .unsupported("Sube el archivo a Drive.")),
    C("Cifra el archivo.", .unsupported("Cifra el archivo.")),
    C("Comprime esto.", .unsupported("Comprime esto.")),
    C("Agenda una reunión.", .unsupported("Agenda una reunión.")),
    C("Imprime el documento.", .unsupported("Imprime el documento.")),
    C("Comparte esto.", .unsupported("Comparte esto.")),
    C("Envía esto por mensaje.", .unsupported("Envía esto por mensaje.")),
    C("Programa un recordatorio.", .unsupported("Programa un recordatorio.")),
    C("Dicta el siguiente párrafo.", .unsupported("Dicta el siguiente párrafo.")),
    C("Lee este párrafo.", .unsupported("Lee este párrafo.")),
    C("Llama a mamá.", .unsupported("Llama a mamá.")),
    C("Exporta como markdown.", .unsupported("Exporta como markdown.")),
    C("Convierte a epub.", .unsupported("Convierte a epub.")),
    C("Busca en internet.", .unsupported("Busca en internet.")),
    C("Cancela la suscripción.", .unsupported("Cancela la suscripción.")),
    // UNKNOWN (dictado, fragmentos, conversación)
    C("La interacción humano computadora estudia sistemas.", .unknown),
    C("Borrar información accidentalmente afecta.", .unknown),
    C("El editor cambia el título solo.", .unknown),
    C("La frase \"borra esto\" es ambigua.", .unknown),
    C("Quiero escribir que guarda solo.", .unknown),
    C("Eso no.", .unknown),
    C("Mejor.", .unknown),
    C("No me gusta.", .unknown),
    C("Ese.", .unknown),
    C("Hmm, no.", .unknown),
    C("No sé.", .unknown),
    C("Tal vez.", .unknown),
    C("Déjame pensarlo.", .unknown),
    C("No estoy seguro.", .unknown),
    C("Espera.", .unknown),
    C("Bueno.", .unknown),
    C("A ver.", .unknown),
    C("Ya veo.", .unknown),
    C("El informe quedó listo ayer.", .unknown),
    C("Guardar silencio comunica.", .unknown),
    C("Abrir debate enriquece.", .unknown),
    C("El gerente cambió al proveedor.", .unknown),
    C("Hace calor aquí.", .unknown),
    C("¿Qué hora es?", .unknown),
    C("", .unknown),
    C(" por favor ", .unknown),
    // MULTI-ACTION
    C("Cambia el título a Resultados y guarda el documento.", .multipleActions),
    C("Borra esto y deshaz el cambio.", .multipleActions),
    C("Ponlo en negritas y guarda.", .multipleActions),
    C("Busca TDAH y selecciónalo.", .multipleActions),
    C("Reemplaza esto por X y archiva el tanto.", .multipleActions),
    C("Hazlo breve y exporta en pdf.", .multipleActions),
    C("Subraya el monto, archiva el oficio.", .multipleActions),
    C("Deshaz el pegado y rehace la numeración.", .multipleActions),
    C("Titula como Balance y guarda copia.", .multipleActions),
    C("Cambia CDMX, guarda y exporta.", .multipleActions),
    C("Tacha el renglón y ponlo en negritas.", .multipleActions),
    C("Limpia y guarda el acta.", .multipleActions),
    // COLISIONES documentadas
    C("Cambia esta palabra por dificultades.", .replaceSelection("dificultades")),
    C("Cambia el título a Resultados.", .renameTitle("Resultados")),
    C("Marca la fecha y localízala.", .multipleActions),
    C("Selecciona todo y márcalo.", .multipleActions),
    C("Busca y marca el folio.", .multipleActions),
    C("Rehaz eso.", .redo),
    C("Deshaz eso.", .undo),
    C("Deshaz el deshacer.", .redo),
    C("Restaura mi edición.", .undo),
    C("Restaura el formato.", .undo),
    C("Guarda una copia como pdf.", .exportDocument(.pdf)),
    C("Guarda el documento.", .saveDocument),
    C("Busca en internet el acta.", .unsupported("Busca en internet el acta.")),
    C("Imprime en pdf virtual.", .unsupported("Imprime en pdf virtual.")),
    C("Convierte a mayúsculas todo.", .unsupported("Convierte a mayúsculas todo.")),
    C("Cuenta las palabras.", .unsupported("Cuenta las palabras.")),
    // Argumentos literales extra (acentos, ñ, siglas, números)
    C("Cambia el título a Evaluación de IHC.", .renameTitle("Evaluación de IHC")),
    C("Busca \"accesibilidad cognitiva\".", .findText("accesibilidad cognitiva")),
    C("Reemplaza esto por Diseño centrado en el usuario.", .replaceSelection("Diseño centrado en el usuario")),
    C("Busca TDAH.", .findText("TDAH")),
    C("Cambia el título a Resultados 2026.", .renameTitle("Resultados 2026")),
    C("Selecciona el otrosí tercero.", .selectText("el otrosí tercero")),
    C("Marca el inciso ñ).", .selectText("el inciso ñ)")),
    C("Toma la gráfica 5-A.", .selectText("la gráfica 5-A")),
    C("Elige el considerando 12º.", .selectText("el considerando 12º")),
    C("Señala a María Félix.", .selectText("a María Félix")),
    C("Encierra al Ñoño.", .selectText("al Ñoño")),
    C("Delimita IHC vs HCI.", .selectText("IHC vs HCI")),
    C("Enfoca el § 4o.", .selectText("el § 4o")),
    C("Ubica TDAH-I.", .findText("TDAH-I")),
    C("Abre el acta Ño. 5.", .openDocument("el acta Ño. 5")),
    C("Carga Fotos 2026/01.", .openDocument("Fotos 2026/01")),
    C("Trae el CV de Muñoz.", .openDocument("el CV de Muñoz")),
    C("Muéstrame Los de abajo.pdf.", .openDocument("Los de abajo.pdf")),
    C("Reabre Tesis_Ñoño_v2.", .openDocument("Tesis_Ñoño_v2")),
    C("Halla la palabra pingüino.", .findText("pingüino")),
    C("Ubica el símbolo €.", .findText("el símbolo €")),
    C("Rastrea el hashtag #TDAH.", .findText("el hashtag #TDAH")),
    C("Caza el 3.5% restante.", .findText("el 3.5% restante")),
    C("Encuentra la diéresis.", .findText("la diéresis")),
    C("Halla comillas «latinas».", .findText("comillas «latinas»")),
    C("Titula la crónica como Ida y vuelta.", .renameTitle("Ida y vuelta")),
    C("El membrete dirá Casa TDAH.", .renameTitle("Casa TDAH")),
    C("Nombra el anexo Ñandú común.", .renameTitle("Ñandú común")),
    C("Que el título cite IHC 2026.", .renameTitle("IHC 2026")),
    C("Ponle 100 años de soledad.", .renameTitle("100 años de soledad")),
    C("Nombre: María-José Pérez.", .renameTitle("María-José Pérez")),
    C("Sustituye pez por pez globo.", .replaceSelection("pez globo")),
    C("Cambia CDMX por Ciudad de México.", .replaceSelection("Ciudad de México")),
    C("Escribe 3.1416 completo.", .replaceSelection("3.1416 completo")),
    C("Troca $100 por cien pesos.", .replaceSelection("cien pesos")),
    C("Pon (sic) tras la cita.", .replaceSelection("(sic)")),
    C("Sustituye etc. por etcétera.", .replaceSelection("etcétera")),
    C("Escribe Niño Héroe.", .replaceSelection("Niño Héroe")),
];

func runGrammarTests() -> (passed: Int, failed: [(String, ParsedCommand, ParsedCommand)]) {
    var passed = 0
    var failed: [(String, ParsedCommand, ParsedCommand)] = []
    for t in grammarTests {
        let got = parseCommand(raw: t.input)
        if got == t.expected { passed += 1 }
        else { failed.append((t.input, t.expected, got)) }
    }
    return (passed, failed)
}
