// Grupos C (120 comandos), D (12 con contexto faltante), E (100 no-órdenes en COMMAND MODE).
import Foundation

let selTDHA = "Las personas con TDAH tienen problemas para escribir."

let groupC: [PipelineTest] = [
    // renameTitle x10
    T("C001", "C", .command, cx(), "Cambia el título a Metodología.", ["renameTitle"], ["newTitle": "Metodología"], true),
    T("C002", "C", .command, cx(), "Pon como título Arquitectura del sistema.", ["renameTitle"], ["newTitle": "Arquitectura del sistema"], true),
    T("C003", "C", .command, cx(), "Cambia el título a Claridad.", ["renameTitle"], ["newTitle": "Claridad"], true),
    T("C004", "C", .command, cx(), "Ponle de título Resultados.", ["renameTitle"], ["newTitle": "Resultados"], true),
    T("C005", "C", .command, cx(), "El nuevo título será Interacción humano computadora.", ["renameTitle"], ["newTitle": "Interacción humano computadora"], true),
    T("C006", "C", .command, cx(), "Actualiza el título a Accesibilidad cognitiva.", ["renameTitle"], ["newTitle": "Accesibilidad cognitiva"], true),
    T("C007", "C", .command, cx(), "Titula esto como Conclusiones.", ["renameTitle"], ["newTitle": "Conclusiones"], true),
    T("C008", "C", .command, cx(), "Quiero que el título sea Metodología.", ["renameTitle"], ["newTitle": "Metodología"], true),
    T("C009", "C", .command, cx(), "Cambia el encabezado a Introducción.", ["renameTitle"], ["newTitle": "Introducción"], true),
    T("C010", "C", .command, cx(), "Modifica el título a Diseño del sistema.", ["renameTitle"], ["newTitle": "Diseño del sistema"], true),
    // deleteSelection x10
    T("C011", "C", .command, cx(sel: selTDHA), "Borra esto.", ["deleteSelection"]),
    T("C012", "C", .command, cx(sel: selTDHA), "Elimina este párrafo.", ["deleteSelection"]),
    T("C013", "C", .command, cx(sel: selTDHA), "Quita esta oración.", ["deleteSelection"]),
    T("C014", "C", .command, cx(sel: "texto seleccionado"), "Borra este texto.", ["deleteSelection"]),
    T("C015", "C", .command, cx(sel: selTDHA), "Suprime lo seleccionado.", ["deleteSelection"]),
    T("C016", "C", .command, cx(sel: selTDHA), "Esto no va, bórralo.", ["deleteSelection"]),
    T("C017", "C", .command, cx(sel: selTDHA), "Descarta esta parte.", ["deleteSelection"]),
    T("C018", "C", .command, cx(sel: selTDHA), "Limpia este párrafo.", ["deleteSelection"]),
    T("C019", "C", .command, cx(sel: "problemas"), "Borra esta palabra.", ["deleteSelection"]),
    T("C020", "C", .command, cx(sel: selTDHA), "Quita eso.", ["deleteSelection"]),
    // replaceSelection x10
    T("C021", "C", .command, cx(sel: "problemas"), "Cambia esta palabra por dificultades.", ["replaceSelection"], ["newText": "dificultades"], true),
    T("C022", "C", .command, cx(sel: selTDHA), "Sustituye esta expresión por algo más claro.", ["replaceSelection"]),
    T("C023", "C", .command, cx(sel: "error"), "Pon errata donde dice error.", ["replaceSelection"], ["newText": "errata"], true),
    T("C024", "C", .command, cx(sel: selTDHA), "Reemplaza este término en todo el documento.", ["replaceSelection"]),
    T("C025", "C", .command, cx(sel: "cosa"), "Cambia cosa por elemento.", ["replaceSelection"], ["newText": "elemento"], true),
    T("C026", "C", .command, cx(sel: selTDHA), "Corrige el nombre del modelo aquí.", ["replaceSelection"]),
    T("C027", "C", .command, cx(sel: "uso"), "Cambia uso por utilización.", ["replaceSelection"], ["newText": "utilización"], true),
    T("C028", "C", .command, cx(sel: selTDHA), "Intercambia el orden de estos párrafos.", ["replaceSelection"]),
    T("C029", "C", .command, cx(sel: "accesibilidad"), "Cambia accesibilidad por inclusión.", ["replaceSelection"], ["newText": "inclusión"], true),
    T("C030", "C", .command, cx(sel: selTDHA), "Sustituye los números por letras.", ["replaceSelection"]),
    // rewriteSelection x10
    T("C031", "C", .command, cx(sel: selTDHA), "Hazlo más corto.", ["rewriteSelection"]),
    T("C032", "C", .command, cx(sel: selTDHA), "Hazlo menos absoluto.", ["rewriteSelection"]),
    T("C033", "C", .command, cx(sel: "Esta oración es demasiado larga."), "Haz este párrafo más claro.", ["rewriteSelection"]),
    T("C034", "C", .command, cx(sel: selTDHA), "Reescribe esto más formal.", ["rewriteSelection"]),
    T("C035", "C", .command, cx(sel: selTDHA), "Hazlo más breve.", ["rewriteSelection"]),
    T("C036", "C", .command, cx(sel: selTDHA), "Reescribe con tono más formal.", ["rewriteSelection"]),
    T("C037", "C", .command, cx(sel: selTDHA), "Hazlo más directo.", ["rewriteSelection"]),
    T("C038", "C", .command, cx(sel: selTDHA), "Simplifica la explicación.", ["rewriteSelection"]),
    T("C039", "C", .command, cx(sel: selTDHA), "Dale otra redacción.", ["rewriteSelection"]),
    T("C040", "C", .command, cx(sel: selTDHA), "Mejora la redacción.", ["rewriteSelection"]),
    // formatSelection x10
    T("C041", "C", .command, cx(sel: selTDHA), "Ponlo en negritas.", ["formatSelection"], ["style": "bold"]),
    T("C042", "C", .command, cx(sel: selTDHA), "Ponlo en cursivas.", ["formatSelection"], ["style": "italic"]),
    T("C043", "C", .command, cx(sel: selTDHA), "Subraya esto.", ["formatSelection"], ["style": "underline"]),
    T("C044", "C", .command, cx(sel: "texto seleccionado"), "Pon esto en negritas.", ["formatSelection"], ["style": "bold"]),
    T("C045", "C", .command, cx(sel: selTDHA), "Pon este texto en cursivas.", ["formatSelection"], ["style": "italic"]),
    T("C046", "C", .command, cx(sel: selTDHA), "Subraya esta parte.", ["formatSelection"], ["style": "underline"]),
    T("C047", "C", .command, cx(sel: selTDHA), "Marca esto en negritas.", ["formatSelection"], ["style": "bold"]),
    T("C048", "C", .command, cx(sel: selTDHA), "Aplica cursivas aquí.", ["formatSelection"], ["style": "italic"]),
    T("C049", "C", .command, cx(sel: selTDHA), "Resalta en negritas.", ["formatSelection"], ["style": "bold"]),
    T("C050", "C", .command, cx(sel: selTDHA), "Ponle subrayado.", ["formatSelection"], ["style": "underline"]),
    // undo x10
    T("C051", "C", .command, cx(undo: true), "Deshaz el último cambio.", ["undo"]),
    T("C052", "C", .command, cx(undo: true), "Deshaz eso.", ["undo"]),
    T("C053", "C", .command, cx(undo: true), "Vuelve a como estaba.", ["undo"]),
    T("C054", "C", .command, cx(undo: true), "No, déjalo como estaba.", ["undo"]),
    T("C055", "C", .command, cx(undo: true), "Revierte lo último.", ["undo"]),
    T("C056", "C", .command, cx(undo: true), "Cancela la última edición.", ["undo"]),
    T("C057", "C", .command, cx(undo: true), "Anula lo que hiciste.", ["undo"]),
    T("C058", "C", .command, cx(undo: true), "Regresa al estado anterior.", ["undo"]),
    T("C059", "C", .command, cx(undo: true), "Échalo para atrás.", ["undo"]),
    T("C060", "C", .command, cx(undo: true), "Deshaz el cambio.", ["undo"]),
    // redo x10
    T("C061", "C", .command, cx(redo: true), "Rehaz el cambio anterior.", ["redo"]),
    T("C062", "C", .command, cx(redo: true), "Rehaz eso.", ["redo"]),
    T("C063", "C", .command, cx(redo: true), "Vuelve a aplicar lo deshecho.", ["redo"]),
    T("C064", "C", .command, cx(redo: true), "Repite la última acción.", ["redo"]),
    T("C065", "C", .command, cx(redo: true), "Recupera lo deshecho.", ["redo"]),
    T("C066", "C", .command, cx(redo: true), "Deshaz el deshacer.", ["redo"]),
    T("C067", "C", .command, cx(redo: true), "Rehaz la edición.", ["redo"]),
    T("C068", "C", .command, cx(redo: true), "Adelante con el cambio.", ["redo"]),
    T("C069", "C", .command, cx(redo: true), "Reaplica el cambio.", ["redo"]),
    T("C070", "C", .command, cx(redo: true), "Rehaz lo anterior.", ["redo"]),
    // selectText x10
    T("C071", "C", .command, cx(), "Selecciona el segundo párrafo.", ["selectText"], ["target": "el segundo párrafo"]),
    T("C072", "C", .command, cx(), "Selecciona todo el documento.", ["selectText"]),
    T("C073", "C", .command, cx(), "Marca esta oración.", ["selectText"]),
    T("C074", "C", .command, cx(), "Elige el tercer párrafo.", ["selectText"]),
    T("C075", "C", .command, cx(), "Selecciona desde aquí hasta el final.", ["selectText"]),
    T("C076", "C", .command, cx(), "Marca todo lo que sigue.", ["selectText"]),
    T("C077", "C", .command, cx(), "Selecciona la palabra anterior.", ["selectText"]),
    T("C078", "C", .command, cx(), "Elige el primer capítulo.", ["selectText"]),
    T("C079", "C", .command, cx(), "Selecciona la cita.", ["selectText"]),
    T("C080", "C", .command, cx(), "Marca el título.", ["selectText"]),
    // findText x10
    T("C081", "C", .command, cx(), "Busca la palabra accesibilidad.", ["findText"], ["query": "accesibilidad"], true),
    T("C082", "C", .command, cx(), "Encuentra la sección de resultados.", ["findText"]),
    T("C083", "C", .command, cx(), "Localiza la cita que falta.", ["findText"]),
    T("C084", "C", .command, cx(), "Busca el párrafo duplicado.", ["findText"]),
    T("C085", "C", .command, cx(), "Encuentra dónde dice conclusiones.", ["findText"]),
    T("C086", "C", .command, cx(), "Busca todas las menciones al autor.", ["findText"]),
    T("C087", "C", .command, cx(), "Localiza el error de dedo.", ["findText"]),
    T("C088", "C", .command, cx(), "Busca la fecha de entrega.", ["findText"], ["query": "fecha de entrega"], true),
    T("C089", "C", .command, cx(), "Encuentra el nombre del modelo.", ["findText"]),
    T("C090", "C", .command, cx(), "Busca comas mal puestas.", ["findText"]),
    // saveDocument x10
    T("C091", "C", .command, cx(), "Guarda el documento.", ["saveDocument"]),
    T("C092", "C", .command, cx(), "Guarda los cambios.", ["saveDocument"]),
    T("C093", "C", .command, cx(), "Guarda una copia.", ["saveDocument"]),
    T("C094", "C", .command, cx(), "Guarda antes de salir.", ["saveDocument"]),
    T("C095", "C", .command, cx(), "Guarda el archivo.", ["saveDocument"]),
    T("C096", "C", .command, cx(), "Guarda el progreso.", ["saveDocument"]),
    T("C097", "C", .command, cx(), "Guarda el informe.", ["saveDocument"]),
    T("C098", "C", .command, cx(), "Guarda esta versión.", ["saveDocument"]),
    T("C099", "C", .command, cx(), "Guarda la carta.", ["saveDocument"]),
    T("C100", "C", .command, cx(), "Guarda el acta.", ["saveDocument"]),
    // openDocument x10
    T("C101", "C", .command, cx(), "Abre el archivo anterior.", ["openDocument"]),
    T("C102", "C", .command, cx(), "Abre el documento adjunto.", ["openDocument"]),
    T("C103", "C", .command, cx(), "Abre la carpeta del proyecto.", ["openDocument"]),
    T("C104", "C", .command, cx(), "Abre el último borrador.", ["openDocument"]),
    T("C105", "C", .command, cx(), "Abre el pdf de referencia.", ["openDocument"]),
    T("C106", "C", .command, cx(), "Abre una ventana nueva.", ["openDocument"]),
    T("C107", "C", .command, cx(), "Abre el contrato.", ["openDocument"]),
    T("C108", "C", .command, cx(), "Abre la tesis.", ["openDocument"]),
    T("C109", "C", .command, cx(), "Abre el manual.", ["openDocument"]),
    T("C110", "C", .command, cx(), "Abre el informe de ayer.", ["openDocument"]),
    // exportDocument x10
    T("C111", "C", .command, cx(), "Exporta el documento.", ["exportDocument"]),
    T("C112", "C", .command, cx(), "Exporta como pdf.", ["exportDocument"]),
    T("C113", "C", .command, cx(), "Exporta a texto plano.", ["exportDocument"]),
    T("C114", "C", .command, cx(), "Genera el pdf para enviar.", ["exportDocument"]),
    T("C115", "C", .command, cx(), "Convierte el archivo a Word.", ["exportDocument"]),
    T("C116", "C", .command, cx(), "Exporta la presentación.", ["exportDocument"]),
    T("C117", "C", .command, cx(), "Exporta la tesis.", ["exportDocument"]),
    T("C118", "C", .command, cx(), "Exporta el manual.", ["exportDocument"]),
    T("C119", "C", .command, cx(), "Exporta el folleto.", ["exportDocument"]),
    T("C120", "C", .command, cx(), "Exporta el informe final.", ["exportDocument"]),
]

// D: COMMAND MODE con contexto insuficiente. La herramienta semántica es correcta;
// el validador debe rechazar. No es error de intención.
let groupD: [PipelineTest] = [
    T("D01", "D", .command, cx(), "Borra esto.", ["deleteSelection"], [:], false, "expect-blocked"),
    T("D02", "D", .command, cx(), "Pon esto en negritas.", ["formatSelection"], [:], false, "expect-blocked"),
    T("D03", "D", .command, cx(), "Hazlo más corto.", ["rewriteSelection"], [:], false, "expect-blocked"),
    T("D04", "D", .command, cx(sel: nil), "Cambia esta palabra por dificultades.", ["replaceSelection"], [:], false, "expect-blocked"),
    T("D05", "D", .command, cx(undo: false), "Deshaz el último cambio.", ["undo"], [:], false, "expect-blocked"),
    T("D06", "D", .command, cx(undo: false), "Vuelve a como estaba.", ["undo"], [:], false, "expect-blocked"),
    T("D07", "D", .command, cx(redo: false), "Rehaz el cambio.", ["redo"], [:], false, "expect-blocked"),
    T("D08", "D", .command, cx(redo: false), "Rehaz lo anterior.", ["redo"], [:], false, "expect-blocked"),
    T("D09", "D", .command, cx(open: false), "Guarda el documento.", ["saveDocument"], [:], false, "expect-blocked"),
    T("D10", "D", .command, cx(open: false), "Exporta el informe.", ["exportDocument"], [:], false, "expect-blocked"),
    T("D11", "D", .command, cx(), "Borra eso.", ["deleteSelection"], [:], false, "expect-blocked"),
    T("D12", "D", .command, cx(), "Ponlo en cursivas.", ["formatSelection"], [:], false, "expect-blocked"),
]

// E: COMMAND MODE sin orden. Ideal: NO TOOL.
let groupE: [PipelineTest] = [
    T("E001", "E", .command, cx(), "Déjame pensarlo."),
    T("E002", "E", .command, cx(), "Hmm, no."),
    T("E003", "E", .command, cx(), "La interacción humano computadora estudia sistemas."),
    T("E004", "E", .command, cx(), "Borrar información accidentalmente puede afectar."),
    T("E005", "E", .command, cx(), "No estoy seguro."),
    T("E006", "E", .command, cx(), "Espera."),
    T("E007", "E", .command, cx(), "No sé."),
    T("E008", "E", .command, cx(), "Tal vez."),
    T("E009", "E", .command, cx(), "Bueno."),
    T("E010", "E", .command, cx(), "Eso no."),
    T("E011", "E", .command, cx(), "Mejor."),
    T("E012", "E", .command, cx(), "Ese."),
    T("E013", "E", .command, cx(), "No me gusta."),
    T("E014", "E", .command, cx(), "Así está bien."),
    T("E015", "E", .command, cx(), "Déjalo."),
    T("E016", "E", .command, cx(), "Hmm."),
    T("E017", "E", .command, cx(), "A ver."),
    T("E018", "E", .command, cx(), "Ya veo."),
    T("E019", "E", .command, cx(), "Entiendo."),
    T("E020", "E", .command, cx(), "De acuerdo."),
    T("E021", "E", .command, cx(), "Interesante."),
    T("E022", "E", .command, cx(), "Vaya."),
    T("E023", "E", .command, cx(), "Mmm."),
    T("E024", "E", .command, cx(), "Vale."),
    T("E025", "E", .command, cx(), "Exacto."),
    T("E026", "E", .command, cx(), "Ajá."),
    T("E027", "E", .command, cx(), "Oh."),
    T("E028", "E", .command, cx(), "Bien."),
    T("E029", "E", .command, cx(), "Ni idea."),
    T("E030", "E", .command, cx(), "Quién sabe."),
    T("E031", "E", .command, cx(), "Puede ser."),
    T("E032", "E", .command, cx(), "Ya."),
    T("E033", "E", .command, cx(), "Listo."),
    T("E034", "E", .command, cx(), "Siguiente."),
    T("E035", "E", .command, cx(), "Continúa."),
    T("E036", "E", .command, cx(), "Te escucho."),
    T("E037", "E", .command, cx(), "Dime."),
    T("E038", "E", .command, cx(), "Un momento."),
    T("E039", "E", .command, cx(), "Pausa."),
    T("E040", "E", .command, cx(), "Sigo."),
    T("E041", "E", .command, cx(), "Adelante."),
    T("E042", "E", .command, cx(), "Durante los últimos años hay interfaces nuevas."),
    T("E043", "E", .command, cx(), "Mi proyecto diseña un editor para TDAH."),
    T("E044", "E", .command, cx(), "Las personas tienen dificultades al escribir."),
    T("E045", "E", .command, cx(), "Guardar documentos reduce el riesgo."),
    T("E046", "E", .command, cx(), "Abrir archivos consume memoria."),
    T("E047", "E", .command, cx(), "Imprimir documentos consume papel."),
    T("E048", "E", .command, cx(), "Buscar información toma tiempo."),
    T("E049", "E", .command, cx(), "Copiar texto introduce duplicados."),
    T("E050", "E", .command, cx(), "Leer en voz alta apoya."),
    T("E051", "E", .command, cx(), "El gerente cambió al proveedor."),
    T("E052", "E", .command, cx(), "La maestra borró el pizarrón."),
    T("E053", "E", .command, cx(), "El mecánico reemplazó la bomba."),
    T("E054", "E", .command, cx(), "Los vecinos cambiaron el nombre."),
    T("E055", "E", .command, cx(), "El comité puso fecha."),
    T("E056", "E", .command, cx(), "El sindicato deshizo recortes."),
    T("E057", "E", .command, cx(), "El restaurante cambió su carta."),
    T("E058", "E", .command, cx(), "Borrar cintas libera estanterías."),
    T("E059", "E", .command, cx(), "Cambiar pañales evita irritaciones."),
    T("E060", "E", .command, cx(), "Poner sal acelera."),
    T("E061", "E", .command, cx(), "Reemplazar la batería extendió la vida."),
    T("E062", "E", .command, cx(), "Eliminar duplicados ordenó todo."),
    T("E063", "E", .command, cx(), "Seleccionar frutas se aprende."),
    T("E064", "E", .command, cx(), "Poner límites evita malentendidos."),
    T("E065", "E", .command, cx(), "El jurado cambió el veredicto."),
    T("E066", "E", .command, cx(), "Seleccionar al azar es imparcial."),
    T("E067", "E", .command, cx(), "El modo dictado desactiva atajos."),
    T("E068", "E", .command, cx(), "La papelera conserva eliminados."),
    T("E069", "E", .command, cx(), "El reemplazo expande abreviaturas."),
    T("E070", "E", .command, cx(), "El corrector sugiere alternativas."),
    T("E071", "E", .command, cx(), "Voy a narrar que cambiar enseña."),
    T("E072", "E", .command, cx(), "Quiero relatar que borrar alivia."),
    T("E073", "E", .command, cx(), "La vista colapsa secciones."),
    T("E074", "E", .command, cx(), "El registro muestra ediciones."),
    T("E075", "E", .command, cx(), "El informe quedó listo ayer."),
    T("E076", "E", .command, cx(), "La propuesta incluye secciones."),
    T("E077", "E", .command, cx(), "El artículo será revisado."),
    T("E078", "E", .command, cx(), "La carta circula."),
    T("E079", "E", .command, cx(), "El ensayo necesita lectura."),
    T("E080", "E", .command, cx(), "La memoria describe el proceso."),
    T("E081", "E", .command, cx(), "El acta apareció hoy."),
    T("E082", "E", .command, cx(), "La reseña recibió comentarios."),
    T("E083", "E", .command, cx(), "El boletín saldrá pronto."),
    T("E084", "E", .command, cx(), "El museo inaugura sala."),
    T("E085", "E", .command, cx(), "El tren amplió recorrido."),
    T("E086", "E", .command, cx(), "La feria reunió editoriales."),
    T("E087", "E", .command, cx(), "El hospital atiende urgencias."),
    T("E088", "E", .command, cx(), "El puente quedó iluminado."),
    T("E089", "E", .command, cx(), "El banco necesita donadores."),
    T("E090", "E", .command, cx(), "El mercado abre domingos."),
    T("E091", "E", .command, cx(), "El parque protege especies."),
    T("E092", "E", .command, cx(), "El acuario renovó el tanque."),
    T("E093", "E", .command, cx(), "Los viernes hay cine."),
    T("E094", "E", .command, cx(), "El observatorio organiza visitas."),
    T("E095", "E", .command, cx(), "El gimnasio abre temprano."),
    T("E096", "E", .command, cx(), "El club compite nacional."),
    T("E097", "E", .command, cx(), "La librería guarda joyas."),
    T("E098", "E", .command, cx(), "Los talleres fomentan lectura."),
    T("E099", "E", .command, cx(), "Las noches permiten ver estrellas."),
    T("E100", "E", .command, cx(), "El pan sigue tibio."),
]
