// Datos de prueba. expectedTools vacío = NO_TOOL esperado.
import Foundation

struct PipelineTest: Sendable {
    let id: String
    let group: String
    let mode: VoiceInteractionMode
    let context: EditorContext
    let voice: String
    let expectedTools: [String]
    let expectedArgs: [String: String]
    let preserveLang: Bool
    let note: String
}

func cx(sel: String? = nil, undo: Bool = false, redo: Bool = false, open: Bool = true) -> EditorContext {
    EditorContext(currentTitle: "Introducción", selectedText: sel,
                  canUndo: undo, canRedo: redo, documentIsOpen: open)
}

func T(_ id: String, _ group: String, _ mode: VoiceInteractionMode,
       _ context: EditorContext, _ voice: String,
       _ expectedTools: [String] = [], _ expectedArgs: [String: String] = [:],
       _ preserveLang: Bool = false, _ note: String = "") -> PipelineTest {
    PipelineTest(id: id, group: group, mode: mode, context: context, voice: voice,
                 expectedTools: expectedTools, expectedArgs: expectedArgs,
                 preserveLang: preserveLang, note: note)
}

// A: MODE=DICTATION con órdenes lingüísticas claras. FM jamás debe llamarse.
let groupA: [PipelineTest] = [
    T("A001", "A", .dictation, cx(), "Cambia el título a Metodología."),
    T("A002", "A", .dictation, cx(), "Borra esto."),
    T("A003", "A", .dictation, cx(), "Guarda el documento."),
    T("A004", "A", .dictation, cx(), "Pon esto en negritas."),
    T("A005", "A", .dictation, cx(), "Deshaz el último cambio."),
    T("A006", "A", .dictation, cx(), "Abre el archivo anterior."),
    T("A007", "A", .dictation, cx(), "Cambia esta palabra por dificultades."),
    T("A008", "A", .dictation, cx(), "Hazlo más corto."),
    T("A009", "A", .dictation, cx(), "Ponlo en cursivas."),
    T("A010", "A", .dictation, cx(), "Subraya esta parte."),
    T("A011", "A", .dictation, cx(), "Rehaz el cambio anterior."),
    T("A012", "A", .dictation, cx(), "Selecciona el segundo párrafo."),
    T("A013", "A", .dictation, cx(), "Busca la palabra accesibilidad."),
    T("A014", "A", .dictation, cx(), "Imprime esta página."),
    T("A015", "A", .dictation, cx(), "Exporta el documento."),
    T("A016", "A", .dictation, cx(), "Cámbialo."),
    T("A017", "A", .dictation, cx(), "Pon eso."),
    T("A018", "A", .dictation, cx(), "Hazlo diferente."),
    T("A019", "A", .dictation, cx(), "Quita esta oración."),
    T("A020", "A", .dictation, cx(), "Elimina este párrafo."),
    T("A021", "A", .dictation, cx(), "Sustituye este término."),
    T("A022", "A", .dictation, cx(), "Reescribe esto más formal."),
    T("A023", "A", .dictation, cx(), "Resume este documento."),
    T("A024", "A", .dictation, cx(), "Hazlo menos absoluto."),
    T("A025", "A", .dictation, cx(), "Pon como título Resultados."),
    T("A026", "A", .dictation, cx(), "Copia este párrafo."),
    T("A027", "A", .dictation, cx(), "Pega aquí el texto."),
    T("A028", "A", .dictation, cx(), "Corta esta sección."),
    T("A029", "A", .dictation, cx(), "Mueve esto al final."),
    T("A030", "A", .dictation, cx(), "Duplica esta página."),
    T("A031", "A", .dictation, cx(), "Lee este párrafo en voz alta."),
    T("A032", "A", .dictation, cx(), "Ve al final del documento."),
    T("A033", "A", .dictation, cx(), "Corrige esta palabra."),
    T("A034", "A", .dictation, cx(), "Traduce esto al inglés."),
    T("A035", "A", .dictation, cx(), "Guarda una copia."),
    T("A036", "A", .dictation, cx(), "Cierra el documento."),
    T("A037", "A", .dictation, cx(), "Abre un archivo nuevo."),
    T("A038", "A", .dictation, cx(), "Comparte esto por correo."),
    T("A039", "A", .dictation, cx(), "Firma este archivo."),
    T("A040", "A", .dictation, cx(), "Comprime el documento."),
    T("A041", "A", .dictation, cx(), "Borra esta oración."),
    T("A042", "A", .dictation, cx(), "Pon esto en cursivas ya."),
    T("A043", "A", .dictation, cx(), "Haz este párrafo más claro."),
    T("A044", "A", .dictation, cx(), "Cambia el título a Claridad."),
    T("A045", "A", .dictation, cx(), "Deshaz eso."),
    T("A046", "A", .dictation, cx(), "Rehaz eso."),
    T("A047", "A", .dictation, cx(), "Selecciona todo."),
    T("A048", "A", .dictation, cx(), "Encuentra la cita."),
    T("A049", "A", .dictation, cx(), "Reemplaza todo."),
    T("A050", "A", .dictation, cx(), "Guarda antes de salir."),
    T("A051", "A", .dictation, cx(), "Imprime dos copias."),
    T("A052", "A", .dictation, cx(), "Exporta como pdf."),
    T("A053", "A", .dictation, cx(), "Abre el pdf adjunto."),
    T("A054", "A", .dictation, cx(), "Lee lo seleccionado."),
    T("A055", "A", .dictation, cx(), "Navega a conclusiones."),
    T("A056", "A", .dictation, cx(), "Inserta una imagen."),
    T("A057", "A", .dictation, cx(), "Agrega una nota."),
    T("A058", "A", .dictation, cx(), "Crea una tabla."),
    T("A059", "A", .dictation, cx(), "Numera las secciones."),
    T("A060", "A", .dictation, cx(), "Genera el índice."),
    T("A061", "A", .dictation, cx(), "Revisa la ortografía."),
    T("A062", "A", .dictation, cx(), "Acepta los cambios."),
    T("A063", "A", .dictation, cx(), "Rechaza la revisión."),
    T("A064", "A", .dictation, cx(), "Comenta este párrafo."),
    T("A065", "A", .dictation, cx(), "Resalta lo importante."),
    T("A066", "A", .dictation, cx(), "Archiva esta versión."),
    T("A067", "A", .dictation, cx(), "Recupera el archivo."),
    T("A068", "A", .dictation, cx(), "Vacía la papelera."),
    T("A069", "A", .dictation, cx(), "Bloquea el documento."),
    T("A070", "A", .dictation, cx(), "Muestra los metadatos."),
    T("A071", "A", .dictation, cx(), "Oculta los cambios."),
    T("A072", "A", .dictation, cx(), "Ajusta los márgenes."),
    T("A073", "A", .dictation, cx(), "Cambia a horizontal."),
    T("A074", "A", .dictation, cx(), "Pon número de página."),
    T("A075", "A", .dictation, cx(), "Alinea a la derecha."),
    T("A076", "A", .dictation, cx(), "Justifica el texto."),
    T("A077", "A", .dictation, cx(), "Convierte a mayúsculas."),
    T("A078", "A", .dictation, cx(), "Pasa a minúsculas."),
    T("A079", "A", .dictation, cx(), "Subraya los verbos."),
    T("A080", "A", .dictation, cx(), "Tacha lo corregido."),
    T("A081", "A", .dictation, cx(), "Agranda la letra."),
    T("A082", "A", .dictation, cx(), "Reduce el cuerpo."),
    T("A083", "A", .dictation, cx(), "Cambia el color."),
    T("A084", "A", .dictation, cx(), "Aplica tema oscuro."),
    T("A085", "A", .dictation, cx(), "Restaura valores."),
    T("A086", "A", .dictation, cx(), "Verifica los datos."),
    T("A087", "A", .dictation, cx(), "Ejecuta el corrector."),
    T("A088", "A", .dictation, cx(), "Previsualiza antes."),
    T("A089", "A", .dictation, cx(), "Sincroniza la nube."),
    T("A090", "A", .dictation, cx(), "Haz respaldo."),
    T("A091", "A", .dictation, cx(), "Fija la fecha."),
    T("A092", "A", .dictation, cx(), "Aplaza la reunión."),
    T("A093", "A", .dictation, cx(), "Adelanta el envío."),
    T("A094", "A", .dictation, cx(), "Cancela la suscripción."),
    T("A095", "A", .dictation, cx(), "Renueva la licencia."),
    T("A096", "A", .dictation, cx(), "Instala la actualización."),
    T("A097", "A", .dictation, cx(), "Reinicia la app."),
    T("A098", "A", .dictation, cx(), "Vuelve a intentarlo."),
    T("A099", "A", .dictation, cx(), "Empieza de nuevo."),
    T("A100", "A", .dictation, cx(), "Termina el documento."),
]

// B: MODE=DICTATION hard negatives. FM jamás debe llamarse.
let groupB: [PipelineTest] = [
    T("B001", "B", .dictation, cx(), "Borrar información accidentalmente puede afectar la experiencia."),
    T("B002", "B", .dictation, cx(), "Guardar documentos automáticamente reduce el riesgo de pérdida."),
    T("B003", "B", .dictation, cx(), "La instrucción \"cambia el título\" aparece en el ejemplo."),
    T("B004", "B", .dictation, cx(), "Deshacer una acción debería ser sencillo."),
    T("B005", "B", .dictation, cx(), "Imprimir documentos consume papel."),
    T("B006", "B", .dictation, cx(), "El editor permite cambiar el título del documento."),
    T("B007", "B", .dictation, cx(), "La función deshacer recupera el contenido anterior."),
    T("B008", "B", .dictation, cx(), "El usuario puede borrar una oración con el teclado."),
    T("B009", "B", .dictation, cx(), "Una interfaz accesible permite seleccionar elementos."),
    T("B010", "B", .dictation, cx(), "El sistema reemplaza algunas palabras solo."),
    T("B011", "B", .dictation, cx(), "Se explica cómo cambiar el formato del texto."),
    T("B012", "B", .dictation, cx(), "Los usuarios ponen palabras en negritas para resaltar."),
    T("B013", "B", .dictation, cx(), "El comando borrar elimina lo seleccionado."),
    T("B014", "B", .dictation, cx(), "Abrir archivos grandes consume memoria."),
    T("B015", "B", .dictation, cx(), "Buscar información toma tiempo."),
    T("B016", "B", .dictation, cx(), "Copiar texto introduce duplicados."),
    T("B017", "B", .dictation, cx(), "Leer en voz alta apoya la revisión."),
    T("B018", "B", .dictation, cx(), "Seleccionar muestra es fundamental."),
    T("B019", "B", .dictation, cx(), "Cambiar el título mejora la claridad."),
    T("B020", "B", .dictation, cx(), "Borrar texto accidentalmente frustra."),
    T("B021", "B", .dictation, cx(), "Deshacer cambios es importante."),
    T("B022", "B", .dictation, cx(), "Reemplazar palabras introduce errores."),
    T("B023", "B", .dictation, cx(), "Poner texto en negritas destaca."),
    T("B024", "B", .dictation, cx(), "La frase \"borra esto\" es ambigua."),
    T("B025", "B", .dictation, cx(), "El usuario puede decir \"cambia el título a Resultados\"."),
    T("B026", "B", .dictation, cx(), "Un ejemplo sería \"pon esto en negritas\"."),
    T("B027", "B", .dictation, cx(), "La documentación dice \"deshaz el último cambio\"."),
    T("B028", "B", .dictation, cx(), "Voy a escribir: cambia esta palabra por dificultades."),
    T("B029", "B", .dictation, cx(), "Es importante cambiar cómo diseñamos interfaces."),
    T("B030", "B", .dictation, cx(), "El título debe comunicar el objetivo."),
    T("B031", "B", .dictation, cx(), "Seleccionar participantes importa."),
    T("B032", "B", .dictation, cx(), "Deshacer una acción debería ser sencillo para el usuario."),
    T("B033", "B", .dictation, cx(), "Quiero escribir que el editor cambia el título solo."),
    T("B034", "B", .dictation, cx(), "La interacción humano computadora estudia sistemas."),
    T("B035", "B", .dictation, cx(), "Durante los últimos años hay interfaces nuevas."),
    T("B036", "B", .dictation, cx(), "Mi proyecto diseña un editor para TDAH."),
    T("B037", "B", .dictation, cx(), "Las personas tienen dificultades al escribir."),
    T("B038", "B", .dictation, cx(), "Guardar silencio también comunica."),
    T("B039", "B", .dictation, cx(), "Abrir debate enriquece la clase."),
    T("B040", "B", .dictation, cx(), "Imprimir carteles difunde eventos."),
    T("B041", "B", .dictation, cx(), "Buscar consenso llevó la tarde."),
    T("B042", "B", .dictation, cx(), "Copiar el esquema ayuda."),
    T("B043", "B", .dictation, cx(), "Pegar avisos informa."),
    T("B044", "B", .dictation, cx(), "Leer el manifiesto conmueve."),
    T("B045", "B", .dictation, cx(), "Exportar café deja divisas."),
    T("B046", "B", .dictation, cx(), "Cerrar tratos conviene."),
    T("B047", "B", .dictation, cx(), "El gerente cambió al proveedor."),
    T("B048", "B", .dictation, cx(), "La maestra borró el pizarrón."),
    T("B049", "B", .dictation, cx(), "El mecánico reemplazó la bomba."),
    T("B050", "B", .dictation, cx(), "Los vecinos cambiaron el nombre."),
    T("B051", "B", .dictation, cx(), "El plomero cambió la tubería."),
    T("B052", "B", .dictation, cx(), "La editorial reemplazó la portada."),
    T("B053", "B", .dictation, cx(), "Los niños borran sus dibujos."),
    T("B054", "B", .dictation, cx(), "El comité puso fecha."),
    T("B055", "B", .dictation, cx(), "La tormenta cambió la sede."),
    T("B056", "B", .dictation, cx(), "El sindicato deshizo recortes."),
    T("B057", "B", .dictation, cx(), "El fotógrafo selecciona tomas."),
    T("B058", "B", .dictation, cx(), "El restaurante cambió su carta."),
    T("B059", "B", .dictation, cx(), "Borrar cintas libera estanterías."),
    T("B060", "B", .dictation, cx(), "Cambiar pañales evita irritaciones."),
    T("B061", "B", .dictation, cx(), "Poner sal acelera la ebullición."),
    T("B062", "B", .dictation, cx(), "Deshacer maletas lleva tiempo."),
    T("B063", "B", .dictation, cx(), "Reemplazar la batería extendió la vida."),
    T("B064", "B", .dictation, cx(), "Eliminar duplicados ordenó todo."),
    T("B065", "B", .dictation, cx(), "Borrar pizarras requiere gesto."),
    T("B066", "B", .dictation, cx(), "Cambiar de carril es peligroso."),
    T("B067", "B", .dictation, cx(), "Seleccionar frutas se aprende."),
    T("B068", "B", .dictation, cx(), "Poner límites evita malentendidos."),
    T("B069", "B", .dictation, cx(), "Eliminar barreras beneficia."),
    T("B070", "B", .dictation, cx(), "Borrar huellas protege privacidad."),
    T("B071", "B", .dictation, cx(), "El jurado cambió el veredicto."),
    T("B072", "B", .dictation, cx(), "Reemplazó la bombilla."),
    T("B073", "B", .dictation, cx(), "El título nobiliario recayó."),
    T("B074", "B", .dictation, cx(), "Poner fin llevó una hora."),
    T("B075", "B", .dictation, cx(), "Seleccionar al azar es imparcial."),
    T("B076", "B", .dictation, cx(), "Borrar es lo más temido."),
    T("B077", "B", .dictation, cx(), "El letrero advierte no borrar."),
    T("B078", "B", .dictation, cx(), "El reglamento dice cambiar contraseñas."),
    T("B079", "B", .dictation, cx(), "El folleto explica seleccionar talla."),
    T("B080", "B", .dictation, cx(), "La receta ordena poner canela."),
    T("B081", "B", .dictation, cx(), "El contrato estipula deshacer compras."),
    T("B082", "B", .dictation, cx(), "La crónica dice que el título se definió."),
    T("B083", "B", .dictation, cx(), "El menú aclara cambiar guarniciones."),
    T("B084", "B", .dictation, cx(), "El acta asienta borrar el punto."),
    T("B085", "B", .dictation, cx(), "La guía recomienda decir siguiente."),
    T("B086", "B", .dictation, cx(), "La nota aclara el título provisional."),
    T("B087", "B", .dictation, cx(), "El aviso dice no cambiar configuración."),
    T("B088", "B", .dictation, cx(), "La etiqueta indica reemplazar."),
    T("B089", "B", .dictation, cx(), "El modo dictado desactiva atajos."),
    T("B090", "B", .dictation, cx(), "La papelera conserva eliminados."),
    T("B091", "B", .dictation, cx(), "El atajo de deshacer es universal."),
    T("B092", "B", .dictation, cx(), "El reemplazo expande abreviaturas."),
    T("B093", "B", .dictation, cx(), "El corrector sugiere alternativas."),
    T("B094", "B", .dictation, cx(), "Voy a narrar que cambiar de ciudad enseña."),
    T("B095", "B", .dictation, cx(), "Quiero relatar que borrar mensajes alivia."),
    T("B096", "B", .dictation, cx(), "Pienso contar que seleccionar temas cuesta."),
    T("B097", "B", .dictation, cx(), "El modo control enumera comandos."),
    T("B098", "B", .dictation, cx(), "El panel centraliza títulos."),
    T("B099", "B", .dictation, cx(), "La vista colapsa secciones."),
    T("B100", "B", .dictation, cx(), "El registro muestra ediciones."),
]
